python:
  - 3.6
  - 3.7
  - 3.8
numpy:
  - 1.14
channel_targets:
  - tudat-team main
channel_sources:
  - msys2, tudat-team, conda-forge, defaults    # [win]
  - tudat-team, conda-forge, defaults           # [not win]
ignore_build_only_deps:
  - numpy
  - python

