python:
  - 3.6
  - 3.7
  - 3.8
numpy:
  - 1.14
eigen:
  - 3.3.7
channel_targets:
  - tudat-team main
channel_sources:
  - tudat-team, conda-forge, defaults
ignore_build_only_deps:
  - numpy
  - python

