{% set name = "tudatpy" %}
  {% set verion = "0.5.22" %}

package:
  name: {{ name }}
  version: {{ verion }}

source:
  - git_url: https://github.com/tudat-team/tudatpy.git
    git_rev: b0bb979abeb865bbf600284ca32666787608de32

build:
  # A non-negative integer representing the build number of the package.
  #  Unlike the build string, the build_number is inspected by conda.
  #  Conda uses it to sort packages that have otherwise identical names
  #  and versions to determine the latest one. This is important because
  #  new builds that contain bug fixes for the way a package is built may be
  #  added to a repository.
  number: 53
  run_exports:
    - {{ pin_compatible('cspice-cmake', max_pin='x.x') }}
    - {{ pin_compatible('tudat-resources', max_pin='x.x') }}
    - {{ pin_compatible('sofa-cmake', max_pin='x.x') }}

requirements:
  build:
    # Tools required to build the package. These packages are run on the build
    # system and include things such as revision control systems (Git, SVN) make
    # tools (GNU make, Autotool, CMake) and compilers (real cross, pseudo-cross,
    # or native when not cross-compiling), and any source pre-processors.
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('clang') }}          # [win]
    - cmake

  host:
    # Packages that need to be specific to the target platform when the
    # target platform is not necessarily the same as the native build
    # platform
    - tudat
    - tudat-resources
    - cspice-cmake
    - sofa-cmake
    - python
    - eigen

  run:
    # Packages required to run the package. These are the dependencies
    # that are installed automatically whenever the package is installed.
    # Package names should follow the package match specifications.
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('pandas') }}
    - {{ pin_compatible('tabulate') }}
    - {{ pin_compatible('tudat') }}
    - python

test:
  imports:
    - tudatpy
    - tudatpy.elements
    - tudatpy.kernel
    - tudatpy.kernel.math
    - tudatpy.kernel.math.interpolators
    - tudatpy.kernel.math.numerical_integrators
    - tudatpy.kernel.math.root_finders
    - tudatpy.kernel.interface
    - tudatpy.kernel.interface.spice_interface
    - tudatpy.kernel.astro
    - tudatpy.kernel.astro.aerodynamics
    - tudatpy.kernel.astro.conversion
    - tudatpy.kernel.astro.ephemerides
    - tudatpy.kernel.astro.fundamentals
    - tudatpy.kernel.astro.gravitation
    - tudatpy.kernel.astro.propagators
    - tudatpy.kernel.astro.frames
    - tudatpy.kernel.astro.shape
    - tudatpy.kernel.astro.two_body_dynamics
    - tudatpy.kernel.constants
    - tudatpy.kernel.io
    - tudatpy.kernel.simulation
    - tudatpy.kernel.simulation.environment_setup
    - tudatpy.kernel.simulation.propagation_setup
    - tudatpy.kernel.simulation.estimation_setup
    - tudatpy.kernel.example

  requires:
    - pytest
  source_files:
    - tests/test_constants.py
    - tests/test_interface_spice.py
    - tests/test_tutorials.py
    - tests/test_io.py

  commands:
    - python -c "from tudatpy.kernel.io import get_resource_path; print(get_resource_path())"
    #- python -c "from tudatpy.apps.satellite_propagator import single; single()"
    - python -m pytest -v tests/test_constants.py
    - python -m pytest -v tests/test_io.py


about:
  home: http://tudat.tudelft.nl/
  license: BSD
  license_family: BSD
  summary: A Python platform to perform astrodynamics and space research.

extra:
  recipe-maintainers:
    - ggarrett13
