{% set name = "tudatpy" %}

package:
  name: {{ name }}
  version: 0.5.4

source:
  git_url: https://github.com/tudat-team/tudatpy.git
  git_rev: 49cf732e5bf0a08f7a8f91211ccb4ab26ab04bb2

build:
  # A non-negative integer representing the build number of the package.
  #  Unlike the build string, the build_number is inspected by conda.
  #  Conda uses it to sort packages that have otherwise identical names
  #  and versions to determine the latest one. This is important because
  #  new builds that contain bug fixes for the way a package is built may be
  #  added to a repository.
#  number: 1
#  skip: true  # [win and vc<14]
  run_exports:
#    - {{ pin_compatible('tudat', max_pin='x.x') }}
    - {{ pin_compatible('cspice-cmake', max_pin='x.x') }}
    - {{ pin_compatible('sofa-cmake', max_pin='x.x') }}

requirements:
  build:
    # Tools required to build the package. These packages are run on the build
    # system and include things such as revision control systems (Git, SVN) make
    # tools (GNU make, Autotool, CMake) and compilers (real cross, pseudo-cross,
    # or native when not cross-compiling), and any source pre-processors.
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('c') }}              # [not win]
    - vs2017_{{ target_platform  }}    # [win]
    - cmake

  host:
    # Packages that need to be specific to the target platform when the
    # target platform is not necessarily the same as the native build
    # platform
    - tudat
    - cspice-cmake
    - sofa-cmake
    - python
    - eigen

  run:
    # Packages required to run the package. These are the dependencies
    # that are installed automatically whenever the package is installed.
    # Package names should follow the package match specifications.
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('pandas') }}
    - {{ pin_compatible('tudat') }}
    - python

about:
  home: http://tudat.tudelft.nl/
  license: BSD
  license_family: BSD
  summary: A Python platform to perform astrodynamics and space research

extra:
  recipe-maintainers:
    - ggarrett13
